### ISSUE TITLE
question about action estimation

### ISSUE THREAD

**Issue by vincentkeino** [yzqin/dexmv-sim#10]
Hello, yuzhe! Thank you for open-sourcing your code, it has been extremely helpful to me. I have a question to ask. In dexmv and dapg, the action_space is defined as 30-d position actuators. Your code uses inverse kinematics to solve for qfrc, which is then converted into actuation as motor commands. This is about physical quantities related to force.However, in subsequent steps, the act_mean and act_rng (span) used are quantities of position actuator joint angles. Could you please explain why the demonstration's action_space is calculated this way? Thank you!

**Comment by vincentkeino** [comment]
Maybe I didn't explain it clearly. My main point of confusion is whether there is any connection between the torque executed by the motor and the position actuator transmitted to the mujoco sim ctrl.

**Comment by yzqin** [comment]
@vincentkeino,

Great question! Although we don't go into too much detail about the action estimation part in the DexMV paper, there is a connection between the torque executed by the motor and the position actuator command. You can find the details of the connection between raw torque and position command [here](https://mujoco.readthedocs.io/en/latest/XMLreference.html#actuator-general), see `gaintype` and `biastype`. 

Essentially, the torque is a linear transformation of the position command (sim ctrl), and this conversion is reversed in the action computation code which can be found [here](https://github.com/yzqin/dexmv-sim/blob/f3815dba0ca3141f2724ad86f413589cd5aa7500/hand_imitation/kinematics/demonstration/base.py#L122).

**Comment by vincentkeino** [comment]
Thank you very much for your answer. Best wishes to you！
