### ISSUE TITLE
visualize_retargeting - ERROR: Shadow framebuffer is not complete, error 0x8cd7

### ISSUE THREAD

**Issue by JingboZeng** [yzqin/dexmv-sim#13]
Hi
I am trying to use your code for retargeting, and am attempting to view the result of visulization. 

I meet a problem when rendering. 
`“ERROR: Shadow framebuffer is not complete, error 0x8cd7”`.
I don't know how to solve this and need help.

I would appreciate any help you have to offer!

**Comment by yzqin** [comment]
Hi @JingboZeng ,

It seems that this is a very general message related to the visualization of your system. It is possible for you to run MuJoCo demo? 

Also you can take a look of the issues [here](https://github.com/openai/mujoco-py/issues/452). Maybe it can help.

**Comment by JingboZeng** [comment]
Hi@yzqin 
I can run the MuJoCo demo, there is no error. And I can correctly get the rendering result.

I have seen the issues in this link, it does work when running demo. But when using your code, this method does not work.

**Comment by yzqin** [comment]
hi @JingboZeng 

Does this error happen for all the DexMV demo or only the retargeting one? Can you please share more information about your system, MuJoCo version? 

Thanks

**Comment by JingboZeng** [comment]
hi @yzqin 
Here are the information about my system

OS: Ubuntu 16.04.12
MuJoCo Version: 2.0
MuJoCo-py Version: 2.0.2.13
python version: 3.7.11

**Comment by yzqin** [comment]
Oh I see. The DexMV code is tested on Ubuntu 18.04, 20.04, and 22.04. I am sorry that I do not have a 16.04 system tested for you. 

If you can run other `mujoco-py` programs but fails on DexMV, one possible reason is some `GLFW` support breaks for Ubuntu 16.04, which will affect [this line of code](https://github.com/yzqin/dexmv-sim/blob/f3815dba0ca3141f2724ad86f413589cd5aa7500/hand_imitation/env/utils/mujoco_py_renderer.py#L50)

**Comment by JingboZeng** [comment]
Thank you for your help.
