### ISSUE TITLE
Some issues with PVN3D

### ISSUE THREAD

**Issue by weixzhang** [yzqin/dexmv-sim#14]
Hi@yzqin,
Thanks for your great work!
I have encountered some problems in the process of using PVN3D. I would like to know if you used the original parameters of PVN3D, or did further training.
Thanks in advance!

**Comment by yzqin** [comment]
Hi @weixzhang ,

We do not use the segmentation module provided by PVN3D but directly feed some external segmentation. To do this, we per-process with some segmentation network to get the segmentation mask. Since the segmentation is well-solved nowadays, you can use some recent SOTA segmentation network to output the mask. In this way, you can get better performance with the per-trained pose estimation network with PVN3D.

**Comment by weixzhang** [comment]
Thank you very much for your reply, it has been very helpful to me！

**Comment by weixzhang** [comment]
I have another question. Did you do the segmentation on the point cloud or on the image? Looking forward to your reply.

**Comment by weixzhang** [comment]
I have another question. Did you do the segmentation on the point cloud or on the image?What is the final input form into PVN3D? 
Can you please explain it to me? Looking forward to your reply.

**Comment by yzqin** [comment]
Segmentation on the image. If you have aligned RGB and depth, you can easily lift the 2D segmentation mask to point cloud. The final input can be the segmented point cloud.

**Comment by xsaxasni** [comment]
Hello, we also use advanced image segmentation methods (which have been verified to be accurate) on the test image (our own scene), but the final object pose effect is improved very little. I would like to ask you how to further process it to get It's the exact pose, thank you very much!

**Comment by yzqin** [comment]
Hi @xsaxasni

You can also apply some post processing for the estimated pose, like ICP (I believe that there will be better alternatives for ICP) and low-pass-filter. Normally the original pose estimated from video will not be so good, like in this project. But we found that even with pose errors in the human demonstration, it still helps for the downstream imitation learning side. So do you worry too much if you do not get a very good pose estimation results.

**Comment by xsaxasni** [comment]
> Hi @xsaxasni
> 
> You can also apply some post processing for the estimated pose, like ICP (I believe that there will be better alternatives for ICP) and low-pass-filter. Normally the original pose estimated from video will not be so good, like in this project. But we found that even with pose errors in the human demonstration, it still helps for the downstream imitation learning side. So do you worry too much if you do not get a very good pose estimation results.

Thank you very much for your reply. The scene we use is not imitation learning, so the pose estimation results required should be better. We will try the method you mentioned, and thank you for your timely reply again!
