### ISSUE TITLE
mujoco_py out of date.

### ISSUE THREAD

**Issue by flydragon2018** [yzqin/dexmv-sim#17]
any plan updating to mujoco?

**Comment by yzqin** [comment]
Hello @flydragon2018, following the conclusion of the DexMV project, we discovered that the MuJoCo simulator doesn't quite meet the requirements of some specific dexterous task. Therefore, we've transitioned to using the [SAPIEN](https://sapien.ucsd.edu/) simulator which offers superior physical simulation capabilities.

Consequently, the repository is provided as-is. We regret to inform you that we won't be updating or maintaining newer versions of MuJoCo.
