### ISSUE TITLE
The global pose of the hand

### ISSUE THREAD

**Issue by YangLiuLewis** [yzqin/dexmv-sim#18]
Hi, Yuzhe. I would like to know what is the global pose of the hand in each frame, since from the paper statement, the pose of palm is the global pose, but I am not sure about it.

**Comment by yzqin** [comment]
Hello @YangLiuLewis, when we refer to the `global pose`, it means the pose is expressed in world coordinates, not in the camera frame. It denotes the wrist's pose in the global world frame. The pose that's estimated by the perception algorithm is in the camera frame. We convert this pose to the global frame using a set transformation (camera extrinsics).
