### ISSUE TITLE
code

### ISSUE THREAD

**Issue by vincentkeino** [yzqin/dexmv-sim#2]

**Comment by vincentkeino** [comment]
hi,thanks for releasing code,it is a great work.but i can not find the code for trajectory generation, time alignment, inverse dynamics and hindsight.it has been "404 not found". can you release it again?

**Comment by yzqin** [comment]
@vincentkeino 

Thanks for pointing out. The link issue has been fixed in the recent commit a7508f07de07f3643719e9c42b9cb5eac2e5802d

**Comment by vincentkeino** [comment]
Thanks,  I can find it! I'll close this issue.
