### ISSUE TITLE
Hand retargeting - What are the results_global_#.npy files? 

### ISSUE THREAD

**Issue by ramialt** [yzqin/dexmv-sim#7]
I'm trying to use your code for hand retargeting, and am attempting to use other hand pose estimation methods (E.g Frankmocap, etc.) to gather MANO hand poses that can be retargeted using your code.

The demo retargeting_human_hand file uses two different types of files as input for the retargeting: joints_#.npy and results_global_#.npy.
 
I understand that joints_*.npy are the 21 joint positions (x, y, z), but I am unsure what the significance is of the results_global_#.npy files. I see these contain 16 4x4 matrices per file, but I'm unsure how they are being used or how they were gathered.

I would appreciate any help you have to offer!

P.S. I am also unsure what the mano_#.npy files signify. They don't seem to be used for retargeting, but I would love to know in any case. They seem to consistently contain arrays of size 61.

**Comment by yzqin** [comment]
Hi @ramialt ,

Thanks for the interest in our work. Sorry that I do not explain it clearly in the README file of this repo.

As you know, the `joints_*.npy` are the joint positions (x, y, z)
The `results_global_#.npy` are related to the pose parameters of MANO hand model. MANO has 45 pose parameters, which is actually 15 * 3 rotation represented in axis-angle (Li Algebra format). Also the wrist of the hand will often have a rotation in the camera space. Thus, there will be 15 + 1 = 16 rotations. We concert the rotation to 4x4 `SE(3)` transformation matrix and saved it into `results_global_#.npy`

One tricky thing to know is that FrankMocap use SMPL-X as the representation but DexMV use MANO. Although MANO and SMPL-X are very similar, they have some tiny different. Please be aware of that.

By the way, I am currently working on a lightweight and standalone python library for `hand pose retargeting`, it includes all the retargeting method used in DexMV and [this paper](https://yzqin.github.io/dex-teleop-imitation/). The code will be released soon as a standalone library, it should be much easier to use compared with the initial retargeting code in this repo.

Thanks!

**Comment by ramialt** [comment]
Thank you for your detailed explanation and advice! That was very helpful. 

A standalone library would be very convenient! When could we expect that to be released? And would it be possible to have some pre-release of that library for re-targeting to an adroit hand?

Thank you again for the great help.

**Comment by priyankamandikal** [comment]
Hi Yuzhe, I have been following this repository as well. It would be super helpful even if a pre-release version (possibly messy) can be provided for retargeting to the adroit hand given an input video.

**Comment by yzqin** [comment]
Hi @priyankamandikal @ramialt ,

I am working on the documentation of this retargeting library now. The initial version should be released around the end of this month.

**Comment by priyankamandikal** [comment]
Hey @yzqin, was the retargeting library made public? I had been routinely checking but couldn't find any release. Thanks!

**Comment by JiaheXu** [comment]
> 

Hi yzqin,

   Any update for the library?

**Comment by yzqin** [comment]
Hi @JiaheXu and @priyankamandikal 

We have some license issue for the model files used in the standalone library. But now you can find a [better retargeting algorithm](https://github.com/yzqin/dex-hand-teleop/tree/main/hand_teleop/kinematics) than the one used in DexMV here in [another repo](https://github.com/yzqin/dex-hand-teleop).

**Comment by yzqin** [comment]
Hi @JiaheXu and @priyankamandikal ,

The retargeting repo can be found [here](https://github.com/dexsuite/dex-retargeting).
