### ISSUE TITLE
About object / hand pose estimation

### ISSUE THREAD

**Issue by ksh960910** [yzqin/dexmv-sim#9]
Hi,
I'm currently trying to get the object / hand pose estimation output from Raw video images. If I'm correct, your work used 
1. PVN3D model for object pose estimation 
2. [this model ](https://arxiv.org/pdf/2106.05266.pdf) for hand pose estimation.
Could you let me know the code lines where the outputs of these pose estimations are?
Also, does these outputs contain 6D / 3D hand poses and 6D object poses too?

I would really appreciate your help.

Best regards,
Joe

**Comment by yzqin** [comment]
Hi Joe,

Sorry I do not understand what do you mean `where the outputs of these pose estimations are?`. Both of these work are open source code that is independent of DexMV.

DexMV needs 6D hand and object pose.

**Comment by ksh960910** [comment]
Thanks for the quick reply.

Sorry if it didn't make sense.
To be short, what I meant was are there codes for section 5.1, 5.2 in your work (Raw Video to 6D pose)

Best regards,
Joe

**Comment by yzqin** [comment]
Hi Joe,

We directly use the third-party open source code from their repo, e.g. `PVN3D` and `Semi-Supervised 3D Hand`. We can refer to these work for detailed description of how to use them.

**Comment by ksh960910** [comment]
Thanks for the details.
Could you send me the raw version of pose estimation by any chance?

Thank you


Best regards,
Joe

2023년 2월 21일 (화) 오전 12:03, Yuzhe Qin ***@***.***>님이 작성:

**Comment by yzqin** [comment]
The estimated pose in this DexMV project can be found here:  https://drive.google.com/file/d/14jWQc2WYGbFsHlwpQ1gatLUh1UXyoEaU/view?usp=sharing
